export const CATEGORIES = [
  "Todos",
  "Core / Abdomen",
  "Glúteos / Cadera",
  "Pierna / Rodilla",
  "Hombro / Escapular",
  "Pecho / Empuje",
  "Espalda / Tracción",
  "Bíceps / Tríceps",
  "Tobillo / Pie",
  "Cervical / Cuello",
  "Muñeca / Mano",
  "Calentamiento",
  "Rehabilitación",
  "Full Body / Funcional",
];

export const EXERCISES = [
  // ── CORE / ABDOMEN ──────────────────────────────────────────────────────
  { id: 1, name: "Plancha frontal", category: "Core / Abdomen", defaultSets: 3, defaultReps: "30 seg", description: "Apoyo de antebrazos y puntas de pies, cuerpo en línea recta, activa abdomen y glúteos." },
  { id: 2, name: "Plancha lateral", category: "Core / Abdomen", defaultSets: 2, defaultReps: "15 seg/lado", description: "Apoyo en antebrazo lateral y pies, mantener el cuerpo alineado y estable." },
  { id: 3, name: "Plancha con toque de hombros (Shoulder tap)", category: "Core / Abdomen", defaultSets: 2, defaultReps: "20 (10/lado)", description: "En posición de plancha alta, tocar con una mano el hombro contrario sin mover el tronco." },
  { id: 4, name: "Plancha comando", category: "Core / Abdomen", defaultSets: 3, defaultReps: "10", description: "Pasar de plancha en antebrazos a plancha en manos de forma controlada." },
  { id: 5, name: "Plancha copenhague", category: "Core / Abdomen", defaultSets: 3, defaultReps: "25 seg/lado", description: "Plancha lateral con pie superior apoyado en superficie elevada, trabaja aductores y core." },
  { id: 6, name: "Plancha + basculación escapular", category: "Core / Abdomen", defaultSets: 3, defaultReps: "12", description: "En posición de plancha, realizar movimiento de protracción y retracción escapular." },
  { id: 7, name: "Press Pallof isométrico", category: "Core / Abdomen", defaultSets: 2, defaultReps: "10 + 10 seg", description: "Con banda o polea a la altura del pecho, extender brazos y mantener posición resistiendo la rotación." },
  { id: 8, name: "Press Pallof dinámico", category: "Core / Abdomen", defaultSets: 2, defaultReps: "10/lado", description: "Igual que el isométrico pero con extensión y retorno de brazos de forma dinámica." },
  { id: 9, name: "Dead Bug", category: "Core / Abdomen", defaultSets: 3, defaultReps: "12", description: "Boca arriba, bajar brazo y pierna opuestos de forma controlada sin perder contacto lumbar con el piso." },
  { id: 10, name: "Bicho muerto con banda en pies", category: "Core / Abdomen", defaultSets: 3, defaultReps: "10/lado", description: "Dead bug con resistencia de banda en dorsiflexión para mayor activación de core anti-rotación." },
  { id: 11, name: "Hollow body hold", category: "Core / Abdomen", defaultSets: 3, defaultReps: "20 seg", description: "Boca arriba, elevar hombros y piernas del piso manteniendo zona lumbar pegada al suelo." },
  { id: 12, name: "V-ups", category: "Core / Abdomen", defaultSets: 3, defaultReps: "10", description: "Desde posición supina, elevar simultáneamente tronco y piernas formando una V." },
  { id: 13, name: "Crunch abdominal isométrico", category: "Core / Abdomen", defaultSets: 3, defaultReps: "10 + 10 seg", description: "Crunch con pausa isométrica al final del recorrido, manteniendo la contracción." },
  { id: 14, name: "Navajas alternadas", category: "Core / Abdomen", defaultSets: 3, defaultReps: "12", description: "Desde posición supina, llevar rodilla al codo del lado contrario de forma alternada." },
  { id: 15, name: "Escuadra (L-Sit)", category: "Core / Abdomen", defaultSets: 3, defaultReps: "20 seg", description: "En paralelas o suelo, elevar y mantener piernas horizontales activando core e isquiotibiales." },
  { id: 16, name: "Rodillo abdominal", category: "Core / Abdomen", defaultSets: 3, defaultReps: "12", description: "Con rodillo abdominal, extender brazos hacia adelante de rodillas controlando la extensión lumbar." },
  { id: 17, name: "Canoa con disco", category: "Core / Abdomen", defaultSets: 2, defaultReps: "20", description: "Sentado con pies elevados, rotar el tronco de lado a lado sosteniendo un disco." },
  { id: 18, name: "Rotación con banda (Woodchopper)", category: "Core / Abdomen", defaultSets: 3, defaultReps: "12/lado", description: "Con banda o polea, realizar movimiento diagonal de rotación de tronco con control." },
  { id: 19, name: "Escaladores", category: "Core / Abdomen", defaultSets: 3, defaultReps: "20", description: "En posición de plancha, llevar rodillas al pecho de forma alternada y rápida." },
  { id: 20, name: "Escaladores cruzados", category: "Core / Abdomen", defaultSets: 3, defaultReps: "15", description: "Igual que escaladores pero llevando la rodilla al codo contrario, activando oblicuos." },

  // ── GLÚTEOS / CADERA ────────────────────────────────────────────────────
  { id: 21, name: "Puente de glúteos", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "15", description: "Boca arriba, pies apoyados, elevar caderas contrayendo glúteos. Se puede agregar pausa arriba." },
  { id: 22, name: "Puente de glúteos isométrico", category: "Glúteos / Cadera", defaultSets: 2, defaultReps: "10 + 10 seg", description: "Puente con pausa isométrica arriba de 5-10 segundos por repetición." },
  { id: 23, name: "Hip thrust", category: "Glúteos / Cadera", defaultSets: 4, defaultReps: "10", description: "Con hombros apoyados en banco y peso en cadera, elevar caderas hasta extensión completa de cadera." },
  { id: 24, name: "Hip thrust unilateral", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "8/lado", description: "Hip thrust a una sola pierna, mayor demanda de glúteo y estabilidad pélvica." },
  { id: 25, name: "Clamshell (Almeja)", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "20/lado", description: "Acostado de lado, rodillas flexionadas, abrir y cerrar la rodilla superior activando glúteo medio." },
  { id: 26, name: "Almeja + isométrico", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "10 + 20 seg", description: "Almeja con pausa isométrica al final de cada repetición o al final de la serie." },
  { id: 27, name: "Extensión de cadera en prono", category: "Glúteos / Cadera", defaultSets: 2, defaultReps: "15/pierna", description: "Acostado boca abajo, elevar una pierna recta contrayendo el glúteo." },
  { id: 28, name: "Abducción de cadera con banda", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "15", description: "De pie o acostado, separar la pierna lateralmente contra la resistencia de una banda." },
  { id: 29, name: "Abducción búlgara con banda en rodillas", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "15", description: "Un pie elevado en pared, llevar la rodilla del pie elevado hacia afuera contra la banda." },
  { id: 30, name: "Caminata lateral con banda (Monster walk)", category: "Glúteos / Cadera", defaultSets: 2, defaultReps: "10 pasos/lado", description: "Con banda en rodillas o tobillos, pasos laterales manteniendo posición semiflexionada." },
  { id: 31, name: "Combo glúteo (pie, sentadilla, bulgara)", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "20/20/20", description: "Combinación de 3 ejercicios de glúteo sin descanso: abducción de pie, en sentadilla y en posición búlgara." },
  { id: 32, name: "Puente en sliders", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "10", description: "Puente de glúteos con pies en sliders, deslizando hacia afuera en la fase excéntrica." },
  { id: 33, name: "Puente en cajón", category: "Glúteos / Cadera", defaultSets: 3, defaultReps: "10", description: "Puente de glúteos con pies elevados en un cajón para mayor rango de movimiento." },

  // ── PIERNA / RODILLA ────────────────────────────────────────────────────
  { id: 34, name: "Sentadilla goblet", category: "Pierna / Rodilla", defaultSets: 4, defaultReps: "10", description: "Sentadilla sosteniendo un peso (KB o mancuerna) frente al pecho, énfasis en profundidad y control." },
  { id: 35, name: "Sentadilla goblet profunda", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "10", description: "Sentadilla goblet llegando a la mayor profundidad posible manteniendo el torso erguido." },
  { id: 36, name: "Búlgara con mancuerna", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "8/pierna", description: "Pie trasero elevado en banco, bajar controlado activando glúteo y cuádriceps de la pierna adelantada." },
  { id: 37, name: "Búlgara con mancuerna lado contrario", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "10/pierna", description: "Búlgara con el peso en la mano del lado contrario para mayor demanda de estabilidad lateral." },
  { id: 38, name: "Step up a cajón", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "8/pierna", description: "Subir al cajón con una pierna de forma controlada, bajar lentamente." },
  { id: 39, name: "Step up con carga excéntrica", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "10", description: "Step up con énfasis en la fase de bajada excéntrica, mancuerna en mano ipsilateral." },
  { id: 40, name: "Sentadilla española (con banda)", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "30 seg/pierna", description: "Con banda jalando la rodilla hacia adelante, realizar sentadilla unilateral para control excéntrico de cuádriceps." },
  { id: 41, name: "Wall sit isométrico", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "30 seg", description: "Espalda apoyada en pared, rodillas a 90°, mantener posición. Se puede agregar balón entre rodillas." },
  { id: 42, name: "Mini sentadillas con pausa isométrica a 45°", category: "Pierna / Rodilla", defaultSets: 2, defaultReps: "10", description: "Sentadilla parcial con pausa isométrica a 45° de flexión, coordinación de patrón sin carga excesiva." },
  { id: 43, name: "Extensión terminal de rodilla con banda (TKE)", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "15", description: "Con banda en parte posterior de rodilla, extender completamente la rodilla. Foco en vasto medial." },
  { id: 44, name: "TKE + abducción pierna contraria", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "15", description: "TKE combinado con abducción de cadera en la pierna no involucrada para integración motriz." },
  { id: 45, name: "Extensión de rodilla (énfasis concéntrico)", category: "Pierna / Rodilla", defaultSets: 2, defaultReps: "Al fallo", description: "En máquina o con banda, extensión de rodilla enfatizando la fase concéntrica con velocidad controlada." },
  { id: 46, name: "Curl femoral acostado (énfasis excéntrico)", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "12", description: "Curl de pierna con énfasis en la fase excéntrica (bajada lenta de 3-4 segundos)." },
  { id: 47, name: "Peso muerto rumano", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "10", description: "Con mancuernas o barra, bisagra de cadera con rodillas ligeramente flexionadas. Énfasis en isquiotibiales." },
  { id: 48, name: "Peso muerto rumano unilateral", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "10/lado", description: "Igual que el rumano pero a una sola pierna, mayor demanda de estabilidad y glúteo." },
  { id: 49, name: "Prensa unilateral", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "10", description: "Prensa de pierna a una sola pierna con énfasis en la fase concéntrica." },
  { id: 50, name: "Sentadilla Cossak isométrica", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "15/lado", description: "Sentadilla lateral profunda con pausa isométrica, trabaja aductores y movilidad de cadera." },
  { id: 51, name: "Pantorrilla con peso", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "Al fallo", description: "Elevación de talones con carga adicional, mantener 2 segundos arriba por repetición." },
  { id: 52, name: "Pantorrilla unilateral", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "Al fallo", description: "Elevación de talón a una pierna sobre step o disco para mayor rango de movimiento." },
  { id: 53, name: "Combo tibial anterior", category: "Pierna / Rodilla", defaultSets: 2, defaultReps: "30-20-10", description: "Tres variantes de flexión dorsal: de pie, sentado, con banda. Sin descanso entre variantes." },
  { id: 54, name: "Plancha copenhague L1 (rehab)", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "20 + 20 seg", description: "Versión inicial de plancha de Copenhague con rodilla apoyada para rehabilitación de aductor." },
  { id: 55, name: "Aducción de Copenhague + rotación", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "30 seg", description: "Plancha de Copenhague con rotación externa añadida para mayor integración." },
  { id: 56, name: "Nordic curl", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "6", description: "Desde arrodillado con pies fijos, caer de forma excéntrica controlada hasta el suelo. Foco en isquiotibiales." },
  { id: 57, name: "Salto al cajón", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "5", description: "Saltar sobre cajón con amortiguación completa al aterrizar, controlando la fase excéntrica." },
  { id: 58, name: "Drop jump", category: "Pierna / Rodilla", defaultSets: 3, defaultReps: "6", description: "Caer de una altura y rebotar inmediatamente, mínimo tiempo de contacto con el suelo." },

  // ── HOMBRO / ESCAPULAR ──────────────────────────────────────────────────
  { id: 59, name: "Retracción escapular", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "12", description: "Apretar omóplatos entre sí y mantener 2 segundos. Se puede hacer con banda en muñecas." },
  { id: 60, name: "Retracción escapular isométrica", category: "Hombro / Escapular", defaultSets: 4, defaultReps: "8 seg", description: "Retracción escapular mantenida en isometría, con o sin banda." },
  { id: 61, name: "Basculación escapular", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "20", description: "En apoyo o colgado, inclinar la escápula hacia adelante y atrás (tilt anterior y posterior)." },
  { id: 62, name: "T-Y-W boca abajo", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "8 reps c/posición", description: "Acostado boca abajo, elevar brazos en posición T, Y y W. Mantener 2-3 segundos arriba." },
  { id: 63, name: "Wall slides con banda", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "Al fallo", description: "Con banda en antebrazos contra la pared, deslizar brazos hacia arriba manteniendo contacto con la pared." },
  { id: 64, name: "Rotación externa con banda (codo pegado)", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "15", description: "Codo a 90° pegado al costado, rotar externamente el hombro contra la resistencia de una banda." },
  { id: 65, name: "Rotación interna con banda", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "15", description: "Codo a 90°, rotar internamente el hombro contra banda o cable bajo." },
  { id: 66, name: "Face pulls con banda", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "15", description: "Jalar banda a la altura de la cara hacia las orejas, retrayendo escápulas al final." },
  { id: 67, name: "Full Can (elevación lateral pulgares arriba)", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "12", description: "Elevación lateral con pulgares apuntando arriba y poco peso. Foco en supraespinoso." },
  { id: 68, name: "Elevaciones laterales", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "12", description: "Elevación lateral de brazos hasta 90°, control en la fase excéntrica." },
  { id: 69, name: "Vuelos laterales (énfasis excéntrico)", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "12", description: "Elevaciones laterales con bajada muy lenta de 3-4 segundos." },
  { id: 70, name: "Vuelos posteriores", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "10", description: "Inclinado hacia adelante, elevar brazos hacia atrás activando deltoides posterior y romboides." },
  { id: 71, name: "Péndulo", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "30 seg/lado", description: "Apoyado en mesa, brazo colgando, hacer círculos pequeños usando el balanceo del cuerpo, no la fuerza." },
  { id: 72, name: "Desliza hacia arriba en pared", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "10", description: "De frente a la pared, deslizar palma hacia arriba descargando el peso del brazo en la pared." },
  { id: 73, name: "Isométrico rotación interna subescapular", category: "Hombro / Escapular", defaultSets: 5, defaultReps: "45 seg", description: "Isometría de rotación interna de hombro para activación selectiva del subescapular." },
  { id: 74, name: "Excéntrico rotación interna (tempo 4-1-4)", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "8", description: "Rotación interna con 4 segundos excéntrico, 1 de pausa y 4 concéntrico. Rehabilitación de manguito." },
  { id: 75, name: "Nadadores (boca abajo)", category: "Hombro / Escapular", defaultSets: 2, defaultReps: "12", description: "Acostado boca abajo, alternar elevación de brazos y piernas como si nadara." },
  { id: 76, name: "Círculos escapulares en pared", category: "Hombro / Escapular", defaultSets: 4, defaultReps: "8", description: "Manos en la pared con codos flexionados, hacer círculos con una mano mientras la otra permanece fija." },
  { id: 77, name: "Press Arnold", category: "Hombro / Escapular", defaultSets: 3, defaultReps: "10", description: "Press de hombro con rotación: empezar con palmas hacia adentro y rotar hasta palmas afuera al extender." },

  // ── PECHO / EMPUJE ──────────────────────────────────────────────────────
  { id: 78, name: "Push up convencional", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "Al fallo", description: "Flexión de brazos en posición de plancha, cuerpo recto, codos a 45° del tronco." },
  { id: 79, name: "Push up inclinado", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "Al fallo", description: "Push up con manos en superficie elevada, menor demanda, útil en rehabilitación o como regresión." },
  { id: 80, name: "Push up en TRX", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "Al fallo", description: "Push up con manos en TRX, mayor inestabilidad y demanda de estabilización escapular." },
  { id: 81, name: "Hand-release push up", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "8", description: "Bajar completamente al piso, soltar las manos y volver a posición de plancha antes de empujar." },
  { id: 82, name: "Bench press con mancuernas", category: "Pecho / Empuje", defaultSets: 4, defaultReps: "10", description: "Press de pecho en banco plano con mancuernas, control en la fase excéntrica." },
  { id: 83, name: "Bench press inclinado con mancuernas", category: "Pecho / Empuje", defaultSets: 4, defaultReps: "10", description: "Press en banco inclinado para mayor énfasis en porción clavicular del pectoral." },
  { id: 84, name: "Press militar con mancuernas", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "8", description: "Press de hombros sentado o de pie con mancuernas, control en todo el rango de movimiento." },
  { id: 85, name: "Landmine press unilateral", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "10/lado", description: "Con barra en landmine, press unilateral desde el hombro hacia arriba y adelante." },
  { id: 86, name: "Push press con KB o barra", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "8", description: "Press de hombro con impulso de piernas para mayor carga. Movimiento olímpico básico." },
  { id: 87, name: "Thruster", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "8", description: "Sentadilla frontal que termina en press de hombros, movimiento completo de full body." },
  { id: 88, name: "Fondos en paralelas", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "Al fallo", description: "Bajada controlada entre paralelas con cuerpo ligeramente inclinado hacia adelante." },
  { id: 89, name: "Fondos en cajón", category: "Pecho / Empuje", defaultSets: 3, defaultReps: "20", description: "Fondos con manos en cajón y pies apoyados en el suelo o en superficie elevada." },

  // ── ESPALDA / TRACCIÓN ──────────────────────────────────────────────────
  { id: 90, name: "Pull up / Chin up", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "Al fallo", description: "Jalones en barra fija con agarre prono (pull up) o supino (chin up). Priorizar técnica." },
  { id: 91, name: "Pull up australiano (Remo invertido)", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "12", description: "Debajo de barra fija, cuerpo recto, jalar el pecho hacia la barra. Accesible para todos los niveles." },
  { id: 92, name: "Remo con TRX", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "12", description: "Remo en TRX con énfasis en retracción escapular. Se regula la dificultad cambiando el ángulo corporal." },
  { id: 93, name: "Remo con mancuerna (serrucho)", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "8/lado", description: "Con una mano apoyada en banco, jalar la mancuerna hacia la cadera con rotación mínima del tronco." },
  { id: 94, name: "Remo con banda", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "12", description: "Remo horizontal con banda elástica, manteniendo postura erguida y escápulas retraídas." },
  { id: 95, name: "Remo renegado", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "12", description: "En posición de plancha con mancuernas, jalar una mancuerna hacia la cadera sin rotar el tronco." },
  { id: 96, name: "Bird Dog", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "20", description: "Desde cuadrupedia, extender brazo y pierna opuestos de forma controlada. Estabilización lumbar." },
  { id: 97, name: "Bird Dog + toca hombro contrario", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "12/lado", description: "Desde cuadrupedia con rodillas elevadas, la mano toca el hombro contrario de forma alternada." },
  { id: 98, name: "Kettlebell swing", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "15", description: "Bisagra de cadera explosiva con kettlebell, propulsado por glúteos e isquiotibiales." },
  { id: 99, name: "Caminata del granjero", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "20 seg", description: "Caminar con pesas pesadas a los lados del cuerpo manteniendo postura erecta y core activado." },
  { id: 100, name: "Halón individual con mancuerna", category: "Espalda / Tracción", defaultSets: 3, defaultReps: "10/lado", description: "Halón unilateral con mancuerna simulando movimiento de remo en una sola mano." },

  // ── BÍCEPS / TRÍCEPS ────────────────────────────────────────────────────
  { id: 101, name: "Bíceps con mancuerna (supino)", category: "Bíceps / Tríceps", defaultSets: 3, defaultReps: "10", description: "Curl de bíceps con mancuernas, palmas hacia arriba, codos fijos a los costados." },
  { id: 102, name: "Bíceps martillo", category: "Bíceps / Tríceps", defaultSets: 3, defaultReps: "10", description: "Curl con agarre neutro (palmas hacia adentro), trabaja braquiorradial y bíceps." },
  { id: 103, name: "Bíceps inclinado con mancuerna", category: "Bíceps / Tríceps", defaultSets: 3, defaultReps: "10", description: "Curl de bíceps en banco inclinado, mayor estiramiento en posición inicial." },
  { id: 104, name: "Bíceps excéntrico", category: "Bíceps / Tríceps", defaultSets: 3, defaultReps: "8", description: "Curl de bíceps con bajada muy lenta (4-6 segundos) para trabajo excéntrico del tendón." },
  { id: 105, name: "Tríceps copa (francés)", category: "Bíceps / Tríceps", defaultSets: 3, defaultReps: "12", description: "Con mancuerna o disco sobre la cabeza, flexionar y extender codos. Trabaja tríceps largo." },
  { id: 106, name: "Extensión de tríceps con banda", category: "Bíceps / Tríceps", defaultSets: 3, defaultReps: "Al fallo", description: "Extensión de codo con banda desde arriba o desde atrás de la cabeza." },
  { id: 107, name: "Tríceps individual extensión a 90°", category: "Bíceps / Tríceps", defaultSets: 2, defaultReps: "Al fallo", description: "Extensión de tríceps unilateral a 90° de abducción de hombro." },

  // ── TOBILLO / PIE ────────────────────────────────────────────────────────
  { id: 108, name: "Knee to wall (movilización tobillo)", category: "Tobillo / Pie", defaultSets: 3, defaultReps: "10", description: "Talón apoyado, avanzar la rodilla hacia la pared sin que el talón se despegue. Movilidad en dorsiflexión." },
  { id: 109, name: "Círculos de tobillo", category: "Tobillo / Pie", defaultSets: 2, defaultReps: "10/lado", description: "Movimiento lento y controlado de tobillo en todos los rangos: flexión, extensión, inversión, eversión." },
  { id: 110, name: "Elevación de talones en 3 posiciones", category: "Tobillo / Pie", defaultSets: 3, defaultReps: "10+10+10", description: "Elevaciones de talón con pies paralelos, en punta adentro y en punta afuera. Sin descanso entre variantes." },
  { id: 111, name: "Calf raises excéntricos", category: "Tobillo / Pie", defaultSets: 3, defaultReps: "10", description: "Subir con dos pies y bajar con uno solo de forma muy lenta. Trabajo excéntrico del sóleo." },
  { id: 112, name: "Eversión con banda + rotación", category: "Tobillo / Pie", defaultSets: 3, defaultReps: "15", description: "Eversión de tobillo con banda con vector contralateral para integración de peroneos y oblicuos." },
  { id: 113, name: "Arrugar toalla con dedos del pie", category: "Tobillo / Pie", defaultSets: 3, defaultReps: "10", description: "Sentado, arrugar una toalla en el piso usando solo los dedos del pie. Musculatura intrínseca." },
  { id: 114, name: "Equilibrio en un pie", category: "Tobillo / Pie", defaultSets: 3, defaultReps: "30 seg", description: "Pararse en un solo pie manteniendo la cadera nivelada y el arco plantar activo." },
  { id: 115, name: "Pogos", category: "Tobillo / Pie", defaultSets: 3, defaultReps: "10", description: "Saltos cortos y rápidos en puntas de pie, mínimo tiempo de contacto con el suelo." },

  // ── CERVICAL / CUELLO ────────────────────────────────────────────────────
  { id: 116, name: "Retracción cervical", category: "Cervical / Cuello", defaultSets: 3, defaultReps: "20", description: "Llevar la cabeza hacia atrás (doble mentón) de forma lenta y controlada. Sin dolor." },
  { id: 117, name: "Flexión isométrica cervical", category: "Cervical / Cuello", defaultSets: 3, defaultReps: "30 seg", description: "Empujar levemente la frente contra las manos o el piso sin mover el cuello. Boca abajo o de pie." },
  { id: 118, name: "Extensión isométrica cervical", category: "Cervical / Cuello", defaultSets: 3, defaultReps: "30 seg", description: "Manos detrás de la cabeza, empujar hacia atrás de forma isométrica. Boca arriba o de pie." },
  { id: 119, name: "Cuello media luna", category: "Cervical / Cuello", defaultSets: 3, defaultReps: "10", description: "Llevar barbilla al pecho y moverla lentamente de un hombro al otro dibujando una media luna." },
  { id: 120, name: "Rotación cervical", category: "Cervical / Cuello", defaultSets: 2, defaultReps: "10/lado", description: "Girar la cabeza lentamente a cada lado hasta el rango máximo sin dolor." },

  // ── MUÑECA / MANO ────────────────────────────────────────────────────────
  { id: 121, name: "Desviación cubital isométrica", category: "Muñeca / Mano", defaultSets: 5, defaultReps: "20 + 20 seg", description: "Llevar la muñeca hacia el lado del meñique y mantener isometría. Rehabilitación de muñeca." },
  { id: 122, name: "Desviación radial isométrica", category: "Muñeca / Mano", defaultSets: 5, defaultReps: "20 + 20 seg", description: "Llevar la muñeca hacia el lado del pulgar y mantener isometría." },
  { id: 123, name: "Extensión de muñeca isométrica", category: "Muñeca / Mano", defaultSets: 5, defaultReps: "20 + 20 seg", description: "Extender la muñeca hacia arriba y mantener la posición en isometría." },
  { id: 124, name: "Flexión de muñeca isométrica", category: "Muñeca / Mano", defaultSets: 5, defaultReps: "20 + 20 seg", description: "Flexionar la muñeca hacia abajo y mantener la posición en isometría." },
  { id: 125, name: "Pronosupinación con mancuerna", category: "Muñeca / Mano", defaultSets: 3, defaultReps: "10 + 10 seg", description: "Sostener mancuerna verticalmente, rotar el antebrazo de pronación a supinación de forma controlada." },
  { id: 126, name: "Grip con disco o mancuerna", category: "Muñeca / Mano", defaultSets: 4, defaultReps: "10 + 10 seg", description: "Agarrar un disco o mancuerna con fuerza y mantener. Fortalece musculatura de la mano y antebrazo." },
  { id: 127, name: "En arroz: apertura a puño", category: "Muñeca / Mano", defaultSets: 2, defaultReps: "Al fallo", description: "Introducir la mano en arroz y abrir y cerrar el puño contra la resistencia del grano." },

  // ── CALENTAMIENTO ────────────────────────────────────────────────────────
  { id: 128, name: "Inchworm + push up", category: "Calentamiento", defaultSets: 2, defaultReps: "5", description: "Desde de pie, bajar las manos al piso, caminar hasta plancha, hacer un push up y volver." },
  { id: 129, name: "World's Greatest Stretch", category: "Calentamiento", defaultSets: 2, defaultReps: "5/lado", description: "Avanzada con rotación de tronco hacia el lado de la pierna adelantada. Movilidad total." },
  { id: 130, name: "Bear crawl multidireccional", category: "Calentamiento", defaultSets: 2, defaultReps: "15 seg", description: "Cuadrupedia con rodillas elevadas del suelo, desplazarse en todas las direcciones." },
  { id: 131, name: "Sentadilla rusa", category: "Calentamiento", defaultSets: 2, defaultReps: "8", description: "Sentadilla profunda manteniendo talones en el suelo, brazos extendidos al frente." },
  { id: 132, name: "Payasitos (Jumping jacks)", category: "Calentamiento", defaultSets: 1, defaultReps: "20", description: "Saltos con apertura y cierre simultáneo de brazos y piernas. Elevación de frecuencia cardíaca." },
  { id: 133, name: "Skipping bajo", category: "Calentamiento", defaultSets: 1, defaultReps: "20 seg", description: "Marcha exagerada en el lugar elevando rodillas, coordinación y activación neuromuscular." },
  { id: 134, name: "Lunge con torsión de tronco", category: "Calentamiento", defaultSets: 2, defaultReps: "6/lado", description: "Avanzada hacia adelante con rotación del tronco hacia el lado de la pierna adelantada." },
  { id: 135, name: "Avanzada con salto (estocada saltada)", category: "Calentamiento", defaultSets: 2, defaultReps: "8/lado", description: "Avanzada alternando piernas con salto en el cambio. Potencia y coordinación." },
  { id: 136, name: "Hip CARs (círculos de cadera)", category: "Calentamiento", defaultSets: 2, defaultReps: "5/lado", description: "Rotación controlada articular de cadera en máximo rango disponible, lenta y con control." },
  { id: 137, name: "Rotación torácica en cuadrupedia", category: "Calentamiento", defaultSets: 2, defaultReps: "10/lado", description: "Desde cuadrupedia, llevar un codo hacia el techo rotando la columna torácica." },

  // ── REHABILITACIÓN ──────────────────────────────────────────────────────
  { id: 138, name: "Extensión corta de rodilla (con toalla)", category: "Rehabilitación", defaultSets: 3, defaultReps: "20", description: "Colocar toalla bajo el talón, extender la rodilla completamente. Post-operatorio de rodilla." },
  { id: 139, name: "Isométrico de cuádriceps", category: "Rehabilitación", defaultSets: 5, defaultReps: "10 (10 seg)", description: "Apretar la parte posterior de la rodilla contra la camilla o toalla. Máxima fuerza isométrica." },
  { id: 140, name: "Deslizando talón (heel slide)", category: "Rehabilitación", defaultSets: 3, defaultReps: "15 (mantener 10 seg)", description: "Deslizar el talón hacia el glúteo de forma activa y mantener al final. Flexión de rodilla progresiva." },
  { id: 141, name: "Bombeo de pantorrilla", category: "Rehabilitación", defaultSets: 3, defaultReps: "50", description: "Mover el pie arriba y abajo en máxima amplitud para activar la bomba muscular y circulación." },
  { id: 142, name: "Abducción de cadera acostado (post-op)", category: "Rehabilitación", defaultSets: 2, defaultReps: "Al fallo de a 8", description: "De lado, elevar la pierna intervenida hacia arriba de forma controlada." },
  { id: 143, name: "Puente unipodal pierna sana", category: "Rehabilitación", defaultSets: 3, defaultReps: "15", description: "Elevar cadera apoyando solo el pie no intervenido. Mantiene glúteo y evita atrofia." },
  { id: 144, name: "Marcha en el puesto con apoyo completo", category: "Rehabilitación", defaultSets: 3, defaultReps: "30 seg", description: "Marcha lenta en el lugar con conciencia plena del apoyo del pie. Control de carga." },
  { id: 145, name: "Propiocepción en pared", category: "Rehabilitación", defaultSets: 3, defaultReps: "30 seg", description: "Apoyar la mano en la pared y realizar pequeñas perturbaciones para entrenar la propiocepción." },
  { id: 146, name: "Aducción con polea + isométrico", category: "Rehabilitación", defaultSets: 2, defaultReps: "15 + 15 seg", description: "Aducción de cadera con polea o banda con pausa isométrica al final. Rehab de aductor." },
  { id: 147, name: "Lunge isométrico + press pallof", category: "Rehabilitación", defaultSets: 2, defaultReps: "10 + 10 seg", description: "Mantener posición de avanzada isométrica mientras se realiza un press pallof con banda." },
  { id: 148, name: "Foam roller cuádriceps y banda iliotibial", category: "Rehabilitación", defaultSets: 1, defaultReps: "2 min/pierna", description: "Liberación miofascial con rodillo de espuma en cuádriceps y tracto iliotibial." },
  { id: 149, name: "Movilización patelar pasiva", category: "Rehabilitación", defaultSets: 2, defaultReps: "30 seg", description: "Mover la rótula suavemente con los pulgares en todas direcciones. Mejora tracking patelar." },
  { id: 150, name: "Estiramiento nervio cubital", category: "Rehabilitación", defaultSets: 3, defaultReps: "5 deslizamientos", description: "Deslizamiento neural del nervio cubital para movilización nerviosa del codo y muñeca." },

  // ── FULL BODY / FUNCIONAL ────────────────────────────────────────────────
  { id: 151, name: "Turkish Get Up", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "5/lado", description: "Desde el suelo, ponerse de pie manteniendo el brazo extendido con KB o mancuerna. Estabilidad total." },
  { id: 152, name: "Man Maker", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "5", description: "Push up + remo + sentadilla + press. Movimiento completo con mancuernas." },
  { id: 153, name: "Clean a press", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "6/lado", description: "Cargada de KB o mancuerna desde el suelo hasta el hombro, seguida de press de hombro." },
  { id: 154, name: "Wall ball", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "12", description: "Sentadilla con balón medicinal, lanzarlo contra la pared al levantarse y atraparlo al bajar." },
  { id: 155, name: "Burpee", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "8", description: "Desde de pie, caer a plancha, hacer un push up, saltar y llevar manos arriba. Solo con técnica impecable." },
  { id: 156, name: "Snatch individual con KB", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "8/lado", description: "Arranque unilateral con KB desde el suelo o entre las piernas hasta brazo extendido arriba." },
  { id: 157, name: "Lanzamiento de balón al piso (Slam ball)", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "10", description: "Elevar el balón sobre la cabeza y lanzarlo con fuerza al piso. Potencia y coordinación." },
  { id: 158, name: "Lanzamiento lateral de balón", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "10/lado", description: "Con rotación de tronco, lanzar el balón lateralmente contra la pared o al suelo." },
  { id: 159, name: "Lanzamiento frontal de balón", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "10", description: "Lanzar el balón medicinal de frente contra la pared con extensión completa de brazos." },
  { id: 160, name: "Skater jumps", category: "Full Body / Funcional", defaultSets: 3, defaultReps: "6/lado", description: "Saltos laterales aterrizando en un pie, simulando movimiento de patinador. Trabajo excéntrico de glúteo medio." },
];
